name: Publish to Pages

on:
    workflow_dispatch:

jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: print directory
      run: |
        pwd
        ls

    - name: check for changes
      run: git status
      
    - name: Clone BoomTown repo
      run: |
        git clone https://github.com/NateJL/BoomTown /home/runner/work/BoomTownTemp
        cd /home/runner/work/BoomTownTemp
        ls
        git status
      
    - name: print directory V2
      run: |
        pwd
        ls
      
    - name: push to BoomTown
      run: echo "Push to BoomTown repo"