name: Publish to Pages

on:
    workflow_dispatch:

jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: print directory
      run: pwd

    - name: check for changes
      run: git status