name: Publish to Pages

on:
    workflow_dispatch:

jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: install exif tool
      run: sudo apt install libimage-exiftool-perl

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@2e89aa66d0093e4cd14751b3028fc1a179452c2e
      with:
        hugo-version: '0.81.0'

    - name: Hugo Build
      run: hugo --minify

    - name: clean Exif metadata
      run: exiftool -overwrite_original -recurse -all= public/

    - name: publish blog to BoomTown: main
      run: |
#        eval "$(ssh-agent -s)"
        echo pwd
#        ssh-add - <<< "${{ secrets.BLOG_DEPLOY }}"
#        git config --global user.name "Jan Delgado"
#        git config --global user.email "myemail@example.com"

#        git clone git@github.com:jandelgado/blog.git && cd blog
#        git checkout --orphan gh-pages
#        git rm -rf .
#        cp -ar ../public/* .
#        git add .
#        git commit -m "update blog"
#        git push --set-upstream --force origin gh-pages